### ISSUE TITLE
Writing to file+S3 does not work

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#179]
With this config:

```yaml
    resourceLog:
      json:
        file: 'resources.json'
        s3:
          bucket: anz-innovation-revolver-bucket
          path: output/resources.json
      csv:
        file: 'resources.csv'
        s3:
          bucket: anz-innovation-revolver-bucket
          path: output/resources.csv
        reportTags: ['Name', 'Schedule']
      console:
        reportTags: ['Name', 'Schedule']
    auditLog:
      console:
      csv:
        file: audit.csv
        s3:
          bucket: anz-innovation-revolver-bucket
          path: output/audit.csv
        append: false
```

**Comment by simon-anz** [comment]
Looks like the code assumes (by returning early) that both will not be true at the same time:

```typescript
  process(): any {
    if (this.options.file) {
      return this.writeFile();
    }
    if (this.options.s3) {
      return this.writeS3();
    }
  }
```

**Comment by simon-anz** [comment]
If I disable the file output, the S3 fails anyway:
```
2024-02-14 10:23:10.668 INFO    /lib/objectLog.js:110   revolver        Writing data to s3://anz-innovation-revolver-bucket/output/resources.json
2024-02-14 10:23:41.134 ERROR   /lib/accountRevolver.js:142     revolver        failed to write resourcesLog json: Region is missing
```

@alutman-innablr do you have $AWS_REGION set maybe?  I noticed some inconsistency with S3Client failing before.

**Comment by simon-anz** [comment]
With PR #180 and following config:

```yaml
      csv:
        file: 'resources.csv'
        s3:
          bucket: anz-innovation-revolver-bucket
          region: ap-southeast-2
          path: output/resources.csv
        reportTags: ['Name', 'Schedule']
      console:
        reportTags: ['Name', 'Schedule']
    auditLog:
      console:
      csv:
        file: audit.csv
        s3:
          bucket: anz-innovation-revolver-bucket
          region: ap-southeast-2
          path: output/audit.csv
        append: false
```

![image](https://github.com/Innablr/revolver/assets/69175652/26769169-1f2c-4d18-8773-1b8c2488bdf5)
