### ISSUE TITLE
Ensure that resource dump includes which schedules are applied to it

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#181]
So we can tell which ones affect the resources.   Yes, this might require allowing plugins and/or actions to augment resources before saving them, and mess up layer separation.

**Comment by simon-anz** [comment]
Sample output:

```yaml
[
  {
    "resourceId": "i-0c688d35209d7f436",
    "resourceType": "ec2",
    "resourceArn": "arn:aws:ec2:ap-southeast-2:554096786507:volume/i-0c688d35209d7f436",
    "launchTimeUtc": "2024-02-13T22:43:49.000Z",
    "resourceState": "running",
    "resource": {
    ....
    },
    "metadata": {
      "matches": [
        {
          "name": "another20",
          "schedule": "24x7",
          "priority": 20
        },
        {
          "name": "another10",
          "schedule": "24x7",
          "priority": 10
        }
      ]
    }
  },
```
