### ISSUE TITLE
Support for more-advanced "calendar type" power schedules

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#228]
Product should support defining calendars which are used in schedules that include things like Public Holidays (state, national, etc), specified in advanced (especially when used via predefinedSchedules).  This would allow logical schedules like "VictoriaBusinessDays", as is done on mainframe/backend.

**Comment by lyricnz** [comment]
Need to be able to specify a (future) shutdown window for a resource-set without breaking any other schedules already matching that resource.  eg:  a team has "mon-fri 0800-1700" schedule defined, and wants to add a (higher priority) schedule "stop Thu 17th April at 1700;   start Tue 22nd April at 0800" - to power off over the Easter weekend

**Comment by lyricnz** [comment]
Possibly we could implement above using a **matcher** that validates the current _date_ matches some criteria, then a conventional (strict) schedule takes care of the stop/start time?

```yaml
            - name: easter shutdown 2025
              filter:
              - tag: SomeTag|SomeValue
              - type: ec2
              - match_window_start: Thu 17th April 2025 at 1700
              - match_window_end: Tue 22nd April 2025 at 0800
              schedule: 0x7
              priority: 20 # higher than the usual daily schedule
```

The window parameters could support explicit or implicit (default) timezones, with or without times, etc.  Probably using some standard ISO format.

**Comment by lyricnz** [comment]
Sample filter from PR code:

```yaml
            - name: 'everything on during window, but missing period'
              filter:
                - type: ec2
                - accountId: '112233445566'
                - matchWindow:
                    from: '2021-01-01'
                    to: '2022-01-01'
              schedule: '24x7'
              priority: 50
```
