### ISSUE TITLE
HTML output files don't appear to be resolving tokens in filenames

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#268]
With default settings
```yaml
    resourceLog:
      json:
        file: 'output/resources.%name.json'
      csv:
        file: 'output/resources.%name.csv'
        reportTags: ['Name', 'Schedule']
      console:
        reportTags: ['Name', 'Schedule']
      html:
        file: output/report-resource.%name.html

    auditLog:
      console:
      html:
        file: output/report-audit.%name.html
      csv:
        file: output/audit.%name.csv
```

the following files are emitted

![image](https://github.com/Innablr/revolver/assets/122371/6131b3b4-da4d-4c34-b2e4-d3c43ba53fd7)
