### ISSUE TITLE
DB cluster unexpectedly scheduled up

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#290]
Using powercycleCentral with configuration of:

```yaml
            - filter:
              - accountId: '554096786507'
              - id: cloudsnooze-test-rds-cluster
              - type: rdsCluster
              name: 'aws-ecp-main-workload-innovation-6: cluster DB'
              priority: 5
              schedule: Start=11:00|mon;Stop=13:00|mon
```

the workload was started at 11am Wednesday with the following message:

2024-04-03T00:00:00.000Z,554096786507,aws-ecp-main-workload-innovation-6,powercycleCentral,rdsCluster,rds,cloudsnooze-test-rds-cluster,start,success,"[aws-ecp-main-workload-innovation-6: cluster DB]: It's Wed 11:00 +11, availability is from 11:00 till 13:00 all week"
