### ISSUE TITLE
Add SNS or SQS as an audit-log target

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#344]
So other systems can be notified when resources are started/stopped, and take reactive steps. For example disabling/enabling monitoring or alerting.

**Comment by lyricnz** [comment]
Looks like there is some JSON->SQS support already - that may suffice.  Will test.

```
    auditLog:
        # Option to write output to an SQS queue
        sqs:
          url: "https://sqs.ap-southeast-2.amazonaws.com/123456789012/sqs-queue"
          # compress messages before sending to queue, defaults to true
          compress: true
          # attributes can be any key/value string pair and are submitted as message attributes for each SQS message
          attributes:
            costCenter: "1234"
            recordId: "0000001"
```
