### ISSUE TITLE
Use of matchWindow schedule includes the "to" timestamp

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#426]
With a schedule as below, the resources were stopped at 10:15 but not started until 10:45

```yaml
            - name: Test Schedule
              filter:
              - matchWindow:
                  from: '2024-08-21T10:15:00.000+10:00'
                  to: '2024-08-21T10:30:00.000+10:00'
              schedule: '0x7'
              priority: 10
```
